#syntax=docker/dockerfile:1
FROM golang:1.26.1

WORKDIR /app

COPY rabbit/go.mod rabbit/go.sum ./rabbit/
COPY middlewere/go.mod ./middlewere/

WORKDIR /app/rabbit
RUN go mod download

COPY rabbit/ ./
COPY middlewere/ /app/middlewere/

ENV RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
ENV DATABASE_URL=postgres://postgres:postgres@postgres:5432/telemetria?sslmode=disable

RUN CGO_ENABLED=0 GOOS=linux go build -o /my-rabbitmq

CMD ["/my-rabbitmq"]
