#syntax=docker/dockerfile:1
FROM golang:1.26.1

WORKDIR /app

COPY middlewere/go.mod middlewere/validate_test.go middlewere/middleware.go ./

RUN go mod download
RUN go test ./...

CMD ["go", "test", "./..."]
